// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpfjnnoabplgrsvhwbln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZmpubm9hYnBsZ3Jzdmh3YmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTg5NjYsImV4cCI6MjA2OTAzNDk2Nn0.xxFPuaSKoqthoz0rWR_rzBkxIS0uf8gGwFcwNn1vCFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});